# docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from podcast-backend-test

version: '2.1'

services:

  podcast-backend-test:
    depends_on:
      cassandra:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile-server-test
    environment:
      ENV: TEST
      PODCAST_INDEX_API_SECRET: $PODCAST_INDEX_API_SECRET
      PODCAST_INDEX_API_KEY: $PODCAST_INDEX_API_KEY
    container_name: podcast-backend-test
    image: podcast-backend-test
    entrypoint:
      ["./gradlew", "test"]

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra-data:
