# docker-compose -f docker-compose-dev.yml up --build

version: '3.5'

services:

  podcast-backend:
    build:
      context: .
      dockerfile: Dockerfile-local-server
    container_name: podcast-backend
    image: podcast-backend
    ports:
      - "50551:50551"
      - "5005:5005"
    restart: always

  envoy:
    depends_on:
      - podcast-backend
    build:
      context: .
      dockerfile: Dockerfile-envoy
    container_name: envoy
    image: envoy
    ports:
      - "9900:9900"
      - "9901:9901"
    restart: always