# docker-compose -f docker-compose-dev.yml up --build

version: '2.1'

services:

  podcast-backend:
    build:
      context: .
      dockerfile: Dockerfile-local-server
    environment:
      ENV: DEV
      PODCAST_INDEX_API_SECRET: $PODCAST_INDEX_SECRET
      PODCAST_INDEX_API_KEY: $PODCAST_INDEX_KEY
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      JWT_SECRET: $JWT_SECRET
    container_name: podcast-backend
    image: podcast-backend
    ports:
      - "50551:50551"
      - "5005:5005"
    restart: always

  envoy:
    depends_on:
      - podcast-backend
    build:
      context: .
      dockerfile: Dockerfile-envoy
    container_name: envoy
    image: envoy
    ports:
      - "9900:9900"
      - "9901:9901"
    restart: always

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "9042:9042"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5