name: Tests
on:
  - pull_request
jobs:

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Fetch Java & Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build Application & Running tests
        env:
          PODCAST_INDEX_SECRET: ${{ secrets.PODCAST_INDEX_SECRET }}
          PODCAST_INDEX_KEY: ${{ secrets.PODCAST_INDEX_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: TEST
        run: ./gradlew test --no-daemon

      - name: Publising JUnit Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit

      - name: Deploing Gradle Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/tests/integrationTest

#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        if: always()
#        with:
#          check_name: Unit Test Results [Summary & Failed]
#          comment_mode: create new
#          files: build/test-results/**/*.xml