name: Pull Request Pipeline
on:
  - pull_request
jobs:
  test-java:
    name: Building Application and Running Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Fetch Java & Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build Application
        env:
          PODCAST_INDEX_API_SECRET: ${{ secrets.PODCAST_INDEX_API_SECRET }}
          PODCAST_INDEX_API_KEY: ${{ secrets.PODCAST_INDEX_API_KEY }}
        run: ./gradlew test --no-daemon

      - name: Publishing report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Report
          path: build/reports/tests
