name: Pull Request Pipeline
on:
  - pull_request
jobs:

  unit-test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Fetch Java & Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build Application
        env:
          PODCAST_INDEX_SECRET: ${{ secrets.PODCAST_INDEX_SECRET }}
          PODCAST_INDEX_KEY: ${{ secrets.PODCAST_INDEX_KEY }}
          ENV: TEST
        run: ./gradlew test --no-daemon

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit

  integration-test:
    name: Running Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Build Application
        env:
          PODCAST_INDEX_SECRET: ${{ secrets.PODCAST_INDEX_SECRET }}
          PODCAST_INDEX_KEY: ${{ secrets.PODCAST_INDEX_KEY }}
          ENV: TEST
        run: ./gradlew integrationTest --no-daemon

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration test results
          path: build/test-results/test/*.xml
          reporter: java-junit